[platformio]
default_envs = arcinsight

[env:arcinsight]
platform = espressif32@^6.0.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_protocol = esptool

board_upload.flash_size = 8MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv

lib_deps =
    links2004/WebSockets@^2.5.0
    https://github.com/pschatzmann/arduino-libhelix.git
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2

build_flags =
    -DBOARD_HAS_PSRAM

[env:arcinsight-selftest]
extends = env:arcinsight
build_flags = ${env:arcinsight.build_flags} -DARCI_SELFTEST